# Generated by Django 6.0.1 on 2026-02-07 13:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('device_name', models.CharField(max_length=100)),
                ('public_key', models.TextField(help_text='ECDSA public key in PEM format')),
                ('user_identifier', models.CharField(blank=True, help_text='Optional user email or username', max_length=100)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_flagged', models.BooleanField(default=False, help_text='Flagged for suspicious activity')),
                ('failed_attempts', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Trusted Device',
                'verbose_name_plural': 'Trusted Devices',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthenticationChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('nonce', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authenticate.trusteddevice')),
            ],
            options={
                'verbose_name': 'Authentication Challenge',
                'verbose_name_plural': 'Authentication Challenges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('session_token', models.TextField(help_text='JWT token for API authentication')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.trusteddevice')),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthenticationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ENROLLMENT', 'Device Enrollment'), ('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('REPLAY_ATTACK', 'Replay Attack Detected'), ('INVALID_SIGNATURE', 'Invalid Signature'), ('EXPIRED_CHALLENGE', 'Expired Challenge'), ('UNREGISTERED_DEVICE', 'Unregistered Device'), ('SESSION_TERMINATED', 'Session Terminated'), ('DEVICE_DEACTIVATED', 'Device Deactivated')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('success', models.BooleanField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('attack_type', models.CharField(blank=True, max_length=50)),
                ('blockchain_hash', models.CharField(blank=True, help_text='SHA256 hash of event', max_length=66, null=True)),
                ('blockchain_tx_hash', models.CharField(blank=True, help_text='Blockchain transaction hash', max_length=66, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authenticate.trusteddevice')),
            ],
            options={
                'verbose_name': 'Authentication Event',
                'verbose_name_plural': 'Authentication Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'success'], name='authenticat_timesta_e14d0d_idx'), models.Index(fields=['event_type', '-timestamp'], name='authenticat_event_t_7d6b18_idx')],
            },
        ),
    ]
